Added the ability to define custom middleware
jedwardhawkins/ng-gulp pull request #3
Opened 2017-07-17 17:22 UTC by jalbr74

Added the ability to define custom middleware for the serve:production and serve:development tasks.

Users of ng-gulp can now add the file: server/server.js to their projects, and define handlers for HTTP calls, which can be handy for defining mock REST APIs.

An example of defining custom middleware in server/server.js is as follows:

var express = require('express');
var app = express();

app.get('/hello', function(req, res) {
    res.send('Hello from the new and improved mock middleware app!');
});

module.exports = app;

2017-07-19 18:22 UTC, jedwardhawkins requested changes
It looks goo but please update README.md

2017-07-19 18:24 UTC, jedwardhawkins commented on index.js
> +    gulp.task('add-custom-middleware', function() {
Let's just call this 'serve:middleware'

2017-07-19 21:26 UTC, jalbr74 commented
Renamed the task 'add-custom-middleware' to 'serve:middleware', and updated the README.

@jedwardhawkins please review and merge.

Thanks

2017-07-20 19:05 UTC, jedwardhawkins submitted a review, later dismissed

2017-07-20 19:09 UTC, jedwardhawkins approved these changes

2017-07-20 19:09 UTC, merged